#!/bin/bash

[[ ${EUID} -ne 0 ]] && PFX='sudo ' || PFX=''

check_make_ok() {
  if [ $? != 0 ]; then
    echo ""
    echo "Make Failed..."
    echo "Please check the messages and fix any problems. If you're still stuck,"
    echo "then please email all the output and as many details as you can to"
    echo "  projects@drogon.net"
    echo ""
    exit 1
  fi
}

if [ x$1 = "xclean" ]; then
  cd wiringPi
  echo -n "wiringPi:   " ; make clean
  cd ../devLib
  echo -n "DevLib:     " ; make clean
  cd ../gpio
  echo -n "gpio:       " ; make clean
  cd ../examples
  echo -n "Examples:   " ; make clean
  cd Gertboard
  echo -n "Gertboard:  " ; make clean
  cd ../PiFace
  echo -n "PiFace:     " ; make clean
  cd ../q2w
  echo -n "Quick2Wire: " ; make clean
  cd ../PiGlow
  echo -n "PiGlow:     " ; make clean
  exit
fi

if [ x$1 = "xuninstall" ]; then
  cd wiringPi
  echo -n "wiringPi: " ; ${PFX}make uninstall
  cd ../devLib
  echo -n "DevLib:   " ; ${PFX}make uninstall
  cd ../gpio
  echo -n "gpio:     " ; ${PFX}make uninstall
  exit
fi

echo "wiringPi Build script"
echo "====================="
echo

echo
echo "WiringPi Library"
cd wiringPi
${PFX}make uninstall
if [ x$1 = "xstatic" ]; then
  make -j `nproc` static
  check_make_ok
  ${PFX}make install-static
else
  make -j `nproc`
  check_make_ok
  ${PFX}make install
fi
check_make_ok

echo
echo "WiringPi Devices Library"
cd ../devLib
${PFX}make uninstall
if [ x$1 = "xstatic" ]; then
  make -j `nproc` static
  check_make_ok
  ${PFX}make install-static
else
  make -j `nproc`
  check_make_ok
  ${PFX}make install
fi
check_make_ok

echo
echo "GPIO Utility"
cd ../gpio
make -j `nproc`
check_make_ok
${PFX}make install
check_make_ok

# https://forum.armbian.com/topic/5647-nanopi-neo-wiringnp-missing-sunxi_infosys_info/#comment-46415
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
SYS_INFO_SRC="${SCRIPT_DIR}/sys_info"
SYS_INFO_DEST="/etc/sys_info"

echo
echo "Attempting to copy sys_info to ${SYS_INFO_DEST}..."

if [ -f "${SYS_INFO_SRC}" ]; then
  ${PFX}cp "${SYS_INFO_SRC}" "${SYS_INFO_DEST}"
  if [ $? -eq 0 ]; then
    echo "sys_info copied successfully to ${SYS_INFO_DEST}"
  else
    echo "Failed to copy sys_info to ${SYS_INFO_DEST}. Please check permissions."
  fi
else
  echo "Error: sys_info not found at ${SYS_INFO_SRC}. Skipping copy."
fi
